name: train
# seed: 666
device: GPU

datasets:
  common:
    num_parallel_workers: 1
    size: 512
    channel: 3
    batch_size: 2
    agm:
      rot90: False
      crop: True
      affine: True
      hflip: True
      vflip: False
      blur: True
      color: True
      noise: False

  train:
    name: KITS19
    type: CTDS
    path: datasets/kits19/train
    img_re: "case_[0-9]*/ct.npy"
    seg_re: "case_[0-9]*/seg.npy"
    # img_re: "case_00000/ct.npy"
    # seg_re: "case_00000/seg.npy"
    shuffle: True

  val:
    name: KITS19
    type: CTDS
    path: datasets/kits19/val
    img_re: "case_[0-9]*/ct.npy"
    seg_re: "case_[0-9]*/seg.npy"
    agm: False
    batch_size: 1
    shuffle: False

train:
  type: SegTrain
  class: 3
  in_channels: 3
  load_ckpt: weight/train_5_37750.ckpt
  max_epoch: 70
  init_weights: henormal

  loss:
    type: TSHybridLoss

  optim:
    type: AdamW

  scheduler:
    type: CosineDecayLR
    min_lr: 0.00005
    max_lr: 0.00015
    decay_steps: 250000
    warmup: 0

  val:
    ZL_DICE:
      type: TSDiceMetric
      one_channel: 2
    SZ_DICE:
      type: TSDiceMetric
      one_channel: 1


# model:
#   type: ShuffleUnet
#   dropout: 0.5
model:
  type: UNET3PLUS
  n_classes: 2

output:
  print_freq: 100
  save_ckpt_freq: 1
  save_best_ckpt: True
  eval_freq: 1
  save_img: 100
